export const LANDING = '/';
export const SIGN_UP = '/signup';
export const LOG_IN = '/login';
export const HOME = '/home';
export const LOG_OUT = '/logout';
export const DASHBOARD = '/dashboard';
export const PAGES = '/PAGES';
// export const ACCOUNT = '/account';
// export const ADMIN = '/admin';
